language: java
addons:
  sonarcloud:
    organization: "csys-fresher-batch-2019"
    token:
      secure: "7a12f2bcbaf5e2591758517c5d7ce37c75cdedea"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=csys-fresher-batch-2019_hospitalapp-anusha
